name: Katalon CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Download Katalon Runtime Engine
        run: |
          curl -L -o katalon.zip "https://download.katalon.com/9.0.0/Katalon_Studio_Engine_Windows_64-9.0.0.zip"
          powershell -Command "Expand-Archive katalon.zip -DestinationPath C:\\katalon"

      - name: Run Katalon Test
        run: |
          "C:\katalon\Katalon_Studio_Engine_Windows_64-9.0.0\katalonc.exe" ^
          -noSplash ^
          -runMode=console ^
          -projectPath="%cd%\CASE01_v2.prj" ^
          -retry=0 ^
          -testSuitePath="Test Suites/TS_DataDriven_Form" ^
          -executionProfile="default" ^
          -browserType="Chrome (headless)" ^
          -reportFolder="Reports" ^
          -apiKey="${{ secrets.KATALON_API_KEY }}"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: katalon-reports
          path: Reports
